# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'node-6':
    docker:
      - image: circleci/node:6
    working_directory: ~/crc16-ccitt
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  'node-latest':
    docker:
      - image: circleci/node:latest
    working_directory: ~/crc16-ccitt
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - 'node-6'
      - 'node-latest'
